### ISSUE TITLE
ReadTheDocs: Create and document Framework in Detail

### ISSUE THREAD

**Issue by dvonthenen** [codedellemc/scaleio-framework#103]
Provide detailed documentation on framework capabilities, operational behavior, flags, etc.

**Comment by dvonthenen** [comment]
After the release of 0.2.0, this will be placed at the top of the list.

**Comment by kacole2** [comment]
let me know where you would like my help here.

**Comment by dvonthenen** [comment]
First stab at the documentation has been completed. The latest can be found here:
http://scaleio-framework.readthedocs.io/en/latest/

Any feedback, things to add, things to remove, and etc would be appreciated.

**Comment by dvonthenen** [comment]
Updated the docs based on feedback. This PR https://github.com/codedellemc/scaleio-framework/pull/130 represents the last commit to the docs before the release. Marking this issue as resolved.

Will continue to update the docs based on added features to the project.
